[package]
name = "mcp-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
rmcp = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

[[example]]
name = "calculator-stdio"
path = "src/calculator_stdio.rs"
